import os

# --- load .env variables before anything else ---
try:
    from dotenv import load_dotenv
    load_dotenv()  # Loads variables from .env at project root, if found
except ImportError:
    pass  # dotenv is in requirements.txt, so this should succeed; if not, continue as normal

from fastapi import FastAPI, status, Request
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import aiohttp

# --- Application Metadata with OpenAPI Tags ---
app = FastAPI(
    title="TestAssist AI Chat Backend",
    description=(
        "Backend API for chatbot answering application testing questions. "
        "All answers are generated live by Google Gemini with answers.txt injected as prompt context."
    ),
    version="2.0.0",
    openapi_tags=[
        {"name": "health", "description": "Health check endpoint"},
        {"name": "chat", "description": "Chat/answer endpoints (Gemini only)"},
        {"name": "llm", "description": "Gemini integration info"},
    ]
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

ANSWERS_FILE = os.path.join(os.path.dirname(__file__), "answers.txt")

# --- Models ---

# PUBLIC_INTERFACE
class ChatQuery(BaseModel):
    """Model for a user query to the chat/answer endpoint."""
    question: str = Field(..., description="User's question about application testing.")

# PUBLIC_INTERFACE
class ChatAnswer(BaseModel):
    """Model for answer response from Gemini."""
    answer: str = Field(..., description="Answer generated by Gemini.")
    from_gemini: bool = Field(True, description="Always true: answer is generated by Gemini.")


# --- Dependency: Strict Gemini API Config Check ---

async def require_gemini_config():
    """
    Raises a 400 error if either GEMINI_API_KEY or GEMINI_API_URL is missing.
    Returns (api_url, api_key) if both are present.
    """
    missing = []
    api_url = os.getenv("GEMINI_API_URL")
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_url:
        missing.append("GEMINI_API_URL")
    if not api_key:
        missing.append("GEMINI_API_KEY")
    if missing:
        detail = {
            "error": "Gemini API configuration error",
            "message": "Required environment variable(s) missing.",
            "missing": missing
        }
        raise FastAPIHTTP400(detail)
    return api_url, api_key

# Custom Exception for 400 error
class FastAPIHTTP400(Exception):
    def __init__(self, detail):
        self.detail = detail

@app.exception_handler(FastAPIHTTP400)
async def fastapi_http_400_handler(request: Request, exc: FastAPIHTTP400):
    return JSONResponse(
        status_code=status.HTTP_400_BAD_REQUEST,
        content=exc.detail,
    )

# --- Core Logic: Answers.txt context ---

def get_answers_txt_context():
    """
    Loads the full answers.txt Q&A content for injection into Gemini prompt.
    Returns an instruction plus all Q&A pairs.
    """
    try:
        with open(ANSWERS_FILE, "r", encoding="utf-8") as f:
            qa_content = f.read().strip()
        if qa_content:
            return (
                "The following Q&A pairs from 'answers.txt' are authoritative; always use these as your primary source. "
                "If you find a matching question, answer precisely as in answers.txt. "
                "If not found, use your own expertise.\n"
                "----- BEGIN ANSWERS.TXT -----\n"
                f"{qa_content}\n"
                "----- END ANSWERS.TXT -----\n"
            )
    except Exception:
        pass
    return ""  # Should not reach here, but contextless fallback

# --- Gemini API Integration ---

# PUBLIC_INTERFACE
async def query_gemini_live(prompt: str, api_url: str, api_key: str) -> str:
    """
    Actually queries the Gemini API using user's prompt with answers.txt included as context.
    Returns the best answer from Gemini or raises for real HTTP errors.
    """

    context = get_answers_txt_context()
    full_prompt = f"{context}\nUser question: {prompt}" if context else prompt

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }
    json_payload = {
        "contents": [
            {
                "parts": [
                    {"text": full_prompt}
                ]
            }
        ]
    }

    async with aiohttp.ClientSession() as session:
        async with session.post(api_url, headers=headers, json=json_payload) as resp:
            text_resp = await resp.text()
            if resp.status == 200:
                try:
                    data = await resp.json()
                    return (
                        data.get("candidates", [{}])[0]
                            .get("content", {})  # Second nesting for Gemini response
                            .get("parts", [{}])[0]
                            .get("text", "")
                    ) or text_resp
                except Exception:
                    return text_resp
            else:
                raise FastAPIHTTP400({
                    "error": "Gemini API error",
                    "message": f"Gemini responded with HTTP {resp.status}",
                    "body": text_resp
                })

# --- Endpoints ---

# PUBLIC_INTERFACE
@app.get("/", tags=["health"], summary="Health check")
def health_check():
    """Simple always-OK health check endpoint."""
    return {"message": "Healthy"}

# PUBLIC_INTERFACE
@app.post(
    "/answer",
    response_model=ChatAnswer,
    tags=["chat"],
    summary="Get answer to a question (from Gemini only, no fallback)",
    description=(
        "Send any user question. Backend always returns a Gemini-generated answer, "
        "injecting answers.txt as context. If Gemini API config is missing, returns a 400 error."
    ),
    responses={
        400: {"description": "Gemini API misconfiguration or live Gemini error."}
    }
)
async def answer_query(query: ChatQuery):
    """
    All user queries are sent to Google Gemini, with the content of answers.txt included as knowledge context.
    No hardcoded, fallback, or simulated logic is ever used; error is raised for any config issue.
    """
    api_url, api_key = await require_gemini_config()
    answer_text = await query_gemini_live(query.question, api_url, api_key)
    return ChatAnswer(answer=answer_text, from_gemini=True)

# PUBLIC_INTERFACE
@app.post(
    "/chat",
    response_model=ChatAnswer,
    tags=["chat"],
    summary="Chat endpoint (same as /answer, uses Gemini only)",
    description=(
        "Chat interface endpoint. Functions identically to /answer; Gemini answers "
        "every query using answers.txt as context. Returns error if config missing."
    ),
    responses={
        400: {"description": "Gemini API misconfiguration or live Gemini error."}
    }
)
async def chat_interface(query: ChatQuery):
    """
    Identical to /answer. Chat endpoint for conversational UI.
    """
    return await answer_query(query)

# PUBLIC_INTERFACE
@app.get(
    "/answers",
    tags=["chat"],
    summary="List all Q&A pairs from answers.txt",
    description="Returns all Q&A pairs found in the answers.txt file as reference only.",
)
def list_qa_pairs():
    """
    Returns the full contents of answers.txt file as Q&A pairs, for frontend display/reference
    (not for answer matching).
    """
    pairs = []
    try:
        with open(ANSWERS_FILE, "r", encoding="utf-8") as f:
            lines = [l.strip() for l in f if l.strip()]
        q = a = None
        for line in lines:
            if line.startswith("Q:"):
                if q and a:
                    pairs.append({"question": q, "answer": a})
                q = line[2:].strip()
                a = None
            elif line.startswith("A:"):
                a = line[2:].strip()
            elif a is not None:
                a += " " + line
        if q and a:
            pairs.append({"question": q, "answer": a})
    except Exception:
        pairs = []
    return pairs

# PUBLIC_INTERFACE
@app.get(
    "/llm_info",
    tags=["llm"],
    summary="LLM (Gemini) integration and configuration info",
    description="Details about Gemini API usage and required backend configuration."
)
def llm_info():
    """
    Provides details on how Gemini is used, which env variables are required, and usage policy.
    """
    return {
        "llm_used": "Google Gemini (every answer)",
        "env_vars": ["GEMINI_API_URL", "GEMINI_API_KEY"],
        "policy": (
            "Every answer is generated by Gemini with answers.txt provided as context. "
            "No fallback or simulated logic exists. Questions cannot be matched to the .txt file directly."
        )
    }

# PUBLIC_INTERFACE
@app.get(
    "/docs/ws",
    tags=["llm"],
    summary="WebSocket usage info",
    description="WebSocket API documentation placeholder."
)
def ws_usage():
    """
    Placeholder for potential future WebSocket API. Not implemented.
    """
    return {
        "info": "WebSocket endpoints are not supported at this time. Use /chat (POST) for all chatbot queries."
    }
