from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, List
import os
import aiohttp

app = FastAPI(
    title="TestAssist AI Chat Backend",
    description="Backend API for chatbot answering application testing questions using a local Q&A file and Google Gemini as fallback.",
    version="1.0.0",
    openapi_tags=[
        {"name": "health", "description": "Health check endpoint"},
        {"name": "chat", "description": "Chat/answer endpoints for Q&A"},
        {"name": "llm", "description": "LLM fallback and info for Gemini"},
    ]
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

ANSWERS_FILE = os.path.join(os.path.dirname(__file__), "answers.txt")

# --- Models ---

# PUBLIC_INTERFACE
class ChatQuery(BaseModel):
    """Model for a user query to the chat/answer endpoint."""
    question: str = Field(..., description="User's question about application testing.")

# PUBLIC_INTERFACE
class ChatAnswer(BaseModel):
    """Model for answer response."""
    answer: str = Field(..., description="Answer to the query.")
    from_gemini: bool = Field(..., description="True if the answer was generated by Gemini, False if from the .txt file.")

# --- Internal Logic ---

def parse_answers(filename: str):
    """
    Parse answers.txt containing Q&A pairs and return a list of (question, answer) tuples.
    Each Q&A should start with 'Q:' and 'A:'
    """
    if not os.path.isfile(filename):
        return []
    pairs = []
    with open(filename, "r", encoding="utf-8") as f:
        lines = [l.strip() for l in f if l.strip()]
    q, a = None, None
    for line in lines:
        if line.startswith("Q:"):
            if q and a:
                pairs.append((q, a))
            q = line[2:].strip()
            a = None
        elif line.startswith("A:"):
            a = line[2:].strip()
        elif a is not None:
            a += " " + line  # support multi-line answers
    if q and a:
        pairs.append((q, a))
    return pairs

def find_best_answer(question: str, qa_pairs: List[tuple]) -> Optional[str]:
    """
    Return best matching answer for the user's question, or None if nothing reasonable.
    For demo, use naive case-insensitive substring match or simple similarity.
    """
    import difflib
    qnorm = question.strip().lower()
    threshold = 0.65
    # Try naive match first
    for q, a in qa_pairs:
        if qnorm in q.lower() or q.lower() in qnorm:
            return a
    # Use difflib to find closest match if direct substring not found
    questions = [q for q, _ in qa_pairs]
    best = difflib.get_close_matches(qnorm, questions, n=1, cutoff=threshold)
    if best:
        match_idx = questions.index(best[0])
        return qa_pairs[match_idx][1]
    return None

# --- Gemini Integration ---

# PUBLIC_INTERFACE
async def query_gemini(prompt: str) -> str:
    """
    Query the actual Google Gemini LLM API endpoint for a response to a question,
    including the answers.txt content as part of the context so the LLM
    uses it as the primary source when possible.

    If an actual API endpoint is not configured, returns a simulated Gemini response.

    Uses the API endpoint and API key from environment variables:
    - GEMINI_API_URL: Full URL to Gemini endpoint (e.g., v1beta/models/gemini-pro:generateContent)
    - GEMINI_API_KEY: Bearer API token (Google service account or Gemini key, not hardcoded)
    """
    import json

    GEMINI_API_URL = os.getenv("GEMINI_API_URL", "")
    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

    # Read answers.txt content for context (if available)
    context_str = ""
    try:
        with open(ANSWERS_FILE, "r", encoding="utf-8") as f:
            answers_txt_content = f.read().strip()
            if answers_txt_content:
                context_str = (
                    "The following Q&A pairs from 'answers.txt' provide authoritative information. "
                    "Always use these as your knowledge base when responding if information matches. "
                    "If the relevant answer is not found, then answer with your own knowledge. "
                    "----- BEGIN ANSWERS.TXT -----\n"
                    f"{answers_txt_content}\n"
                    "----- END ANSWERS.TXT -----\n"
                )
    except Exception:
        context_str = ""

    # Gemini expects the prompt as part of a message or content (see official API docs)
    extended_prompt = f"{context_str}\nUser question: {prompt}" if context_str else prompt

    # Fallback to mock if API not configured
    if not GEMINI_API_URL or not GEMINI_API_KEY:
        return f"Simulated Gemini response (answers.txt provided as context):\n\n{extended_prompt}"

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {GEMINI_API_KEY}",
    }

    # Official Gemini (Google AI) API format from documentation
    json_payload = {
        "contents": [
            {
                "parts": [
                    {"text": extended_prompt}
                ]
            }
        ]
        # Optionally, set "generationConfig": ... if needed for model parameters.
    }

    # Make request and handle API response
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(GEMINI_API_URL, headers=headers, json=json_payload) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    # The response format is typically {"candidates":[{"content":{"parts":[{"text":"..."}]}}],...}
                    try:
                        return (
                            data.get("candidates", [{}])[0]
                                .get("content", {})
                                .get("parts", [{}])[0]
                                .get("text", "")
                        )
                    except Exception:
                        return json.dumps(data)
                # Return HTTP status and diagnostic info on error
                error_detail = await resp.text()
                return f"Gemini returned HTTP {resp.status}: {error_detail}"
    except Exception as e:
        return f"Gemini API request failed ({type(e).__name__}): {str(e)}\nPrompt was:\n{extended_prompt}"


# --- Endpoints ---

# PUBLIC_INTERFACE
@app.get("/", tags=["health"], summary="Health check")
def health_check():
    """
    Simple health check endpoint.
    """
    return {"message": "Healthy"}


# PUBLIC_INTERFACE
@app.post(
    "/answer",
    response_model=ChatAnswer,
    tags=["chat"],
    summary="Retrieve an answer for a user query",
    description=(
        "Given a user's question, always send the query to Gemini, providing the full content of answers.txt in the prompt. "
        "Gemini will use answers.txt as its primary knowledge source if possible, "
        "otherwise fall back to its general knowledge. The backend never returns direct answers; "
        "the response is always generated by Gemini."
    ),
)
async def answer_query(query: ChatQuery):
    """
    Returns Gemini's generated answer to the user's question.
    Always provides the content of answers.txt in the prompt/context to Gemini, instructing it to use this as primary reference.
    Never answers directly from answers.txt.
    """
    gemini_resp = await query_gemini(query.question)
    return ChatAnswer(answer=gemini_resp, from_gemini=True)


from fastapi.responses import JSONResponse
from fastapi import status

# PUBLIC_INTERFACE
@app.post(
    "/chat",
    response_model=ChatAnswer,
    tags=["chat"],
    summary="Chat interface (same as /answer)",
    description="Chat endpoint for conversational Q&A. Always returns Gemini's answer; never from answers.txt."
)
async def chat_interface(query: ChatQuery):
    """
    Conversational endpoint for frontend, always delegates to Gemini with answers.txt as system context.
    Checks that required Gemini API configuration is present and returns a user-facing error if missing.
    """
    missing = []
    gemini_api_url = os.getenv("GEMINI_API_URL")
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    if not gemini_api_url:
        missing.append("GEMINI_API_URL")
    if not gemini_api_key:
        missing.append("GEMINI_API_KEY")
    if missing:
        message = "Required configuration variables missing: " + ", ".join(missing)
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={"error": message, "missing": missing},
        )
    return await answer_query(query)


# PUBLIC_INTERFACE
@app.get("/answers", tags=["chat"], summary="List all available Q&A",
         description="Returns all Q&A pairs from the answers.txt file.")
def list_qa_pairs():
    """
    Returns the full list of Q&A pairs available in answers.txt (for frontend review, cannot post questions here).
    """
    qa_pairs = parse_answers(ANSWERS_FILE)
    return [{"question": q, "answer": a} for q, a in qa_pairs]


# PUBLIC_INTERFACE
@app.get("/llm_info", tags=["llm"], summary="LLM/Gemini integration help", description="Information for developers about Gemini integration.")
def llm_info():
    """
    Returns information on how Gemini integration works and environment variable setup.
    """
    return {
        "llm_used": "Google Gemini (all user questions always handled by Gemini; answers.txt is provided for context with every user query)",
        "env_vars": ["GEMINI_API_URL", "GEMINI_API_KEY"],
        "usage_note": (
            "Every question is sent to Gemini, with answers.txt provided as system context. "
            "Gemini is instructed to use answers.txt as its main source of truth if possible, "
            "otherwise fall back to its own general knowledge."
        )
    }


# PUBLIC_INTERFACE
@app.get("/docs/ws", tags=["llm"], summary="WebSocket usage information")
def ws_usage():
    """
    For future upgrade: Instructions for possible real-time/WebSocket API if needed.
    """
    return {
        "info": "WebSocket endpoints are not yet implemented. Use /chat POST for QA. For real-time integration, refer to future documentation."
    }

